//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAppAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyUserLog
    {
        public int LogID { get; set; }
        public string UserID { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<bool> VideoWatched { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
