//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSupport
    {
        public int ContactSupportId { get; set; }
        public string UserId { get; set; }
        public string Mobile { get; set; }
        public string UserMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
