//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelEarning
    {
        public int LevelID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Level1Users { get; set; }
        public Nullable<int> Level2Users { get; set; }
        public Nullable<int> Level3Users { get; set; }
        public Nullable<int> Level4Users { get; set; }
        public Nullable<int> Level5Users { get; set; }
        public Nullable<int> Level6Users { get; set; }
        public Nullable<int> Level7Users { get; set; }
        public Nullable<int> Level8Users { get; set; }
        public Nullable<int> Level9Users { get; set; }
        public Nullable<int> Level10Users { get; set; }
        public Nullable<double> Level1 { get; set; }
        public Nullable<double> Level2 { get; set; }
        public Nullable<double> Level3 { get; set; }
        public Nullable<double> Level4 { get; set; }
        public Nullable<double> Level5 { get; set; }
        public Nullable<double> Level6 { get; set; }
        public Nullable<double> Level7 { get; set; }
        public Nullable<double> Level8 { get; set; }
        public Nullable<double> Level9 { get; set; }
        public Nullable<double> Level10 { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
