//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public int QuizQuestionID { get; set; }
        public string SelectedOption { get; set; }
        public int TimeTaken { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<int> PointEarn { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual QuizPlayer QuizPlayer { get; set; }
        public virtual QuizQuestion QuizQuestion { get; set; }
    }
}
