//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challange
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ChallangeId { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<bool> TemporaryWinner { get; set; }
        public Nullable<System.DateTime> ChallangeStartDateTime { get; set; }
        public Nullable<int> MinimumEntryPoints { get; set; }
        public Nullable<bool> IsRejected { get; set; }
    }
}
