//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelEarningStatu
    {
        public int ID { get; set; }
        public Nullable<bool> LevelHangFireStatus { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
    }
}
