//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> transactionDateTime { get; set; }
        public string UniqueKey { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<double> amount { get; set; }
        public string comment { get; set; }
        public string username { get; set; }
        public string mobilenumber { get; set; }
        public Nullable<int> ConvertedPoints { get; set; }
        public string WithdrawType { get; set; }
        public string AccountNumber { get; set; }
        public string NameInAccount { get; set; }
        public string Bank { get; set; }
        public string IFSCCode { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
